# basic options
title: PvPKing Client
author: Hythen
email: N/A
description: PvPKing Client's Website!
twitter_username: https://twitter.com/PvPKingsNetwork
github_username:  PvPKing-Client

# Build settings
markdown: kramdown
theme: minima
